### ISSUE TITLE
Add basic build instructions

### ISSUE THREAD

**Issue by jgabriel98** [rustic-music-player/rustic#28]
Hello there.
You project seems to be really cool.

I wanted to build it too, but don't have much experience with rust.

Could you provide simple instruction on how to build the project?

**Comment by maxjoehnk** [comment]
Hi

You should be able to build this project using `cargo build` and start it with `cargo run`.
I should probably add an example configuration file but the provider configuration is documented [here](https://docs.rustic.cloud/en/latest/providers/index.html).

This will not include a frontend. You can use the [web-app](https://github.com/rustic-music-player/web-app) and copy the contents of the `dist` folder into a new folder named `static`.

You can also use the packaged builds that can be found [here](https://rustic.cloud/downloads/).
