### ISSUE TITLE
Broken links on Rusic.

### ISSUE THREAD

**Issue by AndreVuillemot160** [rustic-music-player/rustic#31]
Hey, man thanks for your project. But it seems that your website is dead https://ci.maxjoehnk.me/
I can't get binaries of Android version, and Server too.

**Comment by maxjoehnk** [comment]
Have you tried the links on the download page?
https://rustic.cloud/downloads/

They seem to work but I'll check again later.

**Comment by AndreVuillemot160** [comment]
![image](https://user-images.githubusercontent.com/84594011/128741277-80585c48-dc49-4a1a-b0b7-7567527720b3.png)

**Comment by maxjoehnk** [comment]
Could you try again? I've changed some firewall settings and you should've access now.

**Comment by AndreVuillemot160** [comment]
Works! Thanks
